credentials:
  usernames:
    bahda2026:
      email: bahda@amoud.edu.so
      name: Bahda Admin
      password: $2b$12$1oCaxLT4kifuuKAJbBi7LeGDHaK6EE3F715dN8EAN8NOajHouk0GS
      role: admin
cookie:
  expiry_days: 30
  key: some_signature_key
  name: bahda_auth_v2
preauthorized:
  emails:
    - taskforce@amoud.edu.so
