credentials:
  usernames:
    taskforce:
      email: taskforce@amoud.edu.so
      name: Task Force Pilot
      password: $2b$12$KBf.TaKXnSNmpTCfynHTGurFIhUZ5/A.8seGQk1FOs.BC6UPC4Z3e
      role: admin
cookie:
  expiry_days: 30
  key: some_signature_key
  name: bahda_auth_v2
preauthorized:
  emails:
    - taskforce@amoud.edu.so
